version: "3.1"
services:

    db:
      image: mysql:5.7
      container_name: latorder-mysql
      working_dir: /application
      volumes:
        - .:/application
      command: mysqld --init-file="/application/docker-entrypoint-initdb.d/init.sql"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=order_db
        - MYSQL_USER=root
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: latorder-webserver
      depends_on:
        - php-fpm
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: latorder-php-fpm
      depends_on:
        - db
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
        - db:db
      environment:
        DATABASE_URL: mysql://root:root@db:3306/order_db



